name: Pull Request

on:
  pull_request:
    paths:
      - 'maillogger/**'
      - 'tests/**'
      - 'poetry.lock'
      - 'mypy.ini'
      - 'tox.ini'
      - 'Makefile'

jobs:
  lint:
    name: Lint check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Execute lint check
        run: make lint

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Execut test
        run: make test

  audit:
    name: Pipenv check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install poetry safety

      - name: Execute audit
        run: make audit

  mypy:
    name: mypy check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Execute mypy
        run: make mypy
